import Head from 'next/head'
import Zero from '../components/boxs/zero/Zero';
import One from '../components/boxs/One/One';
import Two from '../components/boxs/Two/Two';
import Signup from '../components/UI/Button/Signup';
import styles from "./index.module.scss";
export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next Appp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Zero/>
        <One/>
        <Two/>
        <div className={styles.signup}>
          <Signup/>
        </div>        
      </main>
    </div>
  )
}